version: 2
updates:
  # Github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "NicoFgrx"

  # Github actions for reusable
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/setup-testing"
    schedule:
      interval: "weekly"
    assignees:
      - "NicoFgrx"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "NicoFgrx"

