"""add_mana_to_ctfd

Revision ID: 0e8c7b2d5767
Revises: a02c5bf43407
Create Date: 2024-05-14 20:04:51.596809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8c7b2d5767'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mana', sa.Integer(), server_default="0", nullable=False))
    op.add_column('teams', sa.Column('mana', sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mana')
    op.drop_column('teams', 'mana')
    # ### end Alembic commands ###
