name: Linting
on: 
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout CTFd
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with: 
        repository: CTFd/CTFd
        ref: 4a404265e7f35398bb0fc89fed4e77d1f55c5356 # 3.8.6

    - name: Checkout CTFd-chall-manager
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        path: CTFd/plugins/ctfd_chall_manager

    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.11' # CTFd python version
      
    - name: Install Python deps
      run: |
        pip install -r requirements.txt
    
    - name: Install Python linter
      run: |
        pip install -r CTFd/plugins/ctfd_chall_manager/linting.txt
      
    - name: Run formatter & linters
      run: |
        cd CTFd/plugins/ctfd_chall_manager
        isort --profile=black --check-only .
        black --check --diff .
        pylint . */*.py
